version: "3"

services:
    myapp:
        container_name: myapp
        restart: always
        image: myapp-flask
        env_file: .env
        build: ./myapp
        ports:
            - "8000:8000"
        command: gunicorn -w 1 -b :8000 app:app
        # volumes:
        #     - ./myapp:/home/project/myapp
        networks:
            - app-network

    nginx:
        container_name: nginx
        restart: always
        image: myapp-nginx
        env_file: .env
        build: ./nginx
        ports:
            - "80:80"
        volumes:
            - ./logs/nginx:/var/log/nginx
        depends_on:
            - myapp
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
